<?php

/**
 * @file
 * Contains edu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function edu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the edu module.
    case 'help.page.edu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Educational module for lecture 11') . '</p>';
      return $output;

    default:
  }
}

function edu_theme($existing, $type, $theme, $path) {
    return [
        'comment-template' => [
            'variables' => ['comments' => []],
            'template' => 'edu-field-comment',
        ],
        'time-template' => [
            'variables' => ['data' => []],
            'template' => 'time-field',
        ],
    ];
}

function edu_preprocess(&$variables){
}
